---
title: "flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
```


```{r}
data("rest_inspec") #import the dataset
rest_inspec_df = #create a dataframe
  rest_inspec |> 
  select( #select particular/important columns for plotting
    boro, camis, cuisine_description, dba, score, street, zipcode, grade) |>
  filter(
    grade %in% c("A", "B", "C"), #filter only grades in A, B, and C
    cuisine_description == "American", #filter only American restaurants
    boro == "MANHATTAN" #filter only the Manhattan boro
    )
```

This is a dashboard

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: box plot

```{r}
rest_inspec_df |>
  mutate(street = fct_reorder(street, score)) |>
  plot_ly(y = ~score, color = ~street, type = "box", colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B: scatter plot

```{r}
rest_inspec_df |>
  mutate(text_label = str_c("Name: ", dba, "\nGrade", grade)) |> 
  plot_ly(x = ~street, y = ~score, type = "scatter", mode = "markers", color = ~grade,   text = ~text_label, alpha = 0.5)
```

### Chart C: bar plot

```{r}
rest_inspec_df |>
  count(street) |>
  mutate(street = fct_reorder(street, n)) |>
  plot_ly(x = ~street, y = ~n, color = ~street, type = "bar", colors = "viridis")
```

